### ISSUE TITLE
ub release fájl gondok

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-3-official#1]
1. A release fájlok tartalma egyel magasabb, mint az elérhető csomag(ok)é.

2.Van egy rakás ub, melyben nincs release fájl.

Egy részüknek pótolható a release fájlja, mert az csomagja megtalálható az ftp://ftp.uhulinux.hu/uhu/3/packages/updates és ftp://ftp.uhulinux.hu/uhu/3/packages/new könyvtárban.

Ezek az ily módon pótolhatók:

bcg729
cifs-utils
cups-filters
exfat-utils
fuse-exfat
lsb-release
luasocket
lxpolkit
networkmanager-pptp
opus
opus-tools
perl-authen-sasl
perl-class-factory-util
perl-clone-pp
perl-crypt-rc4
perl-data-printer
perl-datetime-format-builder
perl-datetime-format-pg
perl-datetime-format-strptime
perl-digest-perl-md5
perl-digest-sha3
perl-file-homedir
perl-file-slurp
perl-ipc-run
perl-modern-perl
perl-moosex-nonmoose
perl-net-smtp-ssl
perl-posix-strftime-compiler
perl-readonly
perl-sort-naturally
perl-tap-formatter-junit
perl-test-xml
perl-xml-filter-buffertext
perl-xml-generator
perl-xml-sax-writer
perl-xml-semanticdiff
perl-xml-xpath
pptpclient
python3-dbus
python-apsw
python-cssselect
python-esky
python-mechanize
python-netifaces
python-pyquery
qpdf

Ezeknek nem leltem a csomagját sem:

perl-bit-vector
perl-carp-clan
perl-dbix-connector
perl-net-dbus-glib
perl-net-ntp

**Comment by rezso** [comment]
1. Ezt írtam is.
2. Nincs túl nagy jelentőségük, mivel ez a repó leginkább azért van, hogy ne kelljen svn-ben keresgélni az ub-ket. De ha gondolod, csinálhatsz rá PR-t :)

**Comment by rezso** [comment]
Fixed: https://github.com/uhulinux/ub-3-official/commit/02fd9ed36342dab3a547519078f6752b95b4a4d7
